name: check_manual

on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release

permissions: read-all

jobs:
  verify-manual:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Save current manual
        run: mv doc/zstd_manual.html doc/zstd_manual_saved.html

      - name: Generate new manual
        run: make manual

      - name: Compare manuals
        run: |
          if ! cmp -s doc/zstd_manual.html doc/zstd_manual_saved.html; then
            echo "The manual was not updated before release !"
            exit 1
          fi
